wandb_version: 1

architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.019069977178955193
num_epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696806140.814105
    t:
      1:
      - 1
      - 41
      - 55
      - 63
      2:
      - 1
      - 41
      - 55
      - 63
      3:
      - 16
      - 23
      - 37
      4: 3.9.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
